name: Approve

on:
  pull_request:
    types: [labeled]

jobs:
  approve:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ github.event.label.name == 'Bypass approve' }}
    env:
      GH_TOKEN: ${{ github.token }}
      NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate github token
        id: generate_token
        uses: ./.github/actions/github-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - run: gh pr review $NUMBER --approve
      - run: gh pr edit $NUMBER --remove-reviewer $REVIEWER
        env:
          REVIEWER: ${{ github.event.requested_reviewer.login }}
